name = "ghostb"
prefix = "ghostb"
author = "YonV"
template = "cba"
mainprefix = "z"
folder_optionals = true
sig_version = 3

files = [
    "mod.cpp",
    "README.md",
    "LICENSE",
    "3rdparty/addons",
    "3rdparty/keys",
    "AUTHORS.txt",
    "gobp2_256_g.paa",
    "gobp2_256.paa",
    ]

exclude = ["*.psd", "*.png", "*.tga"]


modname = "{{name}}"
key_name = "{{prefix}}_{{version}}"
authority = "{{prefix}}_{{version}}-{{git \"id 8\"}}"


check = [
    "!compile_scripts"
]

postbuild = [
    "!remove_compiled_scripts"
]

releasebuild = [
    "@zip @ghostb_{{version}}"
]

[header_exts]
version = "{{git \"id 8\"}}"


[scripts.compile_scripts]
steps_windows = [
    "echo 'Compile Arma Scripts'",
    "ArmaScriptCompiler.exe"
]

steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
show_output = true

[scripts.remove_compiled_scripts]
steps_windows = [
    "echo 'remove Compiled Scripts'",
    "powershell -Command Remove-Item './addons/*' -Recurse -Include *.sqfc"
]
steps_linux = [
    "echo 'Compiling Arma Scripts does not work yet on Linux'"
]
only_release = true
show_output = true
